version: 2

sources:
  - name: banco_origen
    database: dataengineerp
    schema: banco_raw # dataset donde estan los csv cargados
    tables:
      - name: raw_clientes
      - name: raw_comercios
      - name: raw_transacciones
